name: Trigger auto deployment for container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'app/**'
    - '.github/workflows/container-app-autodeploy.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          appSourcePath: ${{ github.workspace }}/app
          acrName: apaulture
          containerAppEnvironment: container-app-environment
          containerAppName: container-app
          resourceGroup: apaulture
          disableTelemetry: true
          buildArguments: |
            "MANAGE_ENV=prod"
